name: tastemate_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: any
  mocktail: ^1.0.4
  dio: ^5.7.0
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  curl_logger_dio_interceptor: ^1.0.0
  awesome_dio_interceptor: ^1.2.0
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/generated/
  line_length: 80
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/